// Parity: the TypeScript feature/encoding port must reproduce training/feature_fixtures.json
// (generated by training/export_onnx.py from real StatsBomb shots).

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { interp, pickBucket } from "./calibrate";
import { BUCKET_KEEP, encodeRow, maskGroups, MODEL_FEATURES } from "./encode";
import { featuresFromInput, FEATURE_COLUMNS, presentGroups } from "./features";
import type { ShotInput } from "./types";

const here = new URL(".", import.meta.url).pathname;
const fixtures = JSON.parse(readFileSync(join(here, "__fixtures__/feature_fixtures.json"), "utf8"));
const spec = JSON.parse(readFileSync(join(here, "../../public/model/feature_spec.json"), "utf8"));
const calibrators = JSON.parse(readFileSync(join(here, "../../public/model/calibrators.json"), "utf8"));

const isNil = (v: unknown) => v === null || v === undefined || (typeof v === "number" && Number.isNaN(v));

describe("feature spec agreement", () => {
  it("MODEL_FEATURES matches the shipped ONNX input order", () => {
    expect(MODEL_FEATURES).toEqual(spec.model_features);
  });
  it("FEATURE_COLUMNS matches training", () => {
    expect(FEATURE_COLUMNS).toEqual(spec.feature_columns ?? FEATURE_COLUMNS);
  });
});

describe("featuresFromInput parity", () => {
  for (const c of fixtures.cases) {
    it(`case ${c.shot_id}`, () => {
      const got = featuresFromInput(c.input as ShotInput);
      for (const key of FEATURE_COLUMNS) {
        const exp = c.features[key];
        if (isNil(exp)) {
          expect(isNil(got[key]), `${key} expected nil`).toBe(true);
        } else if (typeof exp === "number") {
          expect(got[key] as number, key).toBeCloseTo(exp, 6);
        } else {
          expect(got[key], key).toBe(exp);
        }
      }
    });
  }
});

describe("encodeRow + maskGroups parity", () => {
  for (const c of fixtures.cases) {
    const feats = featuresFromInput(c.input as ShotInput);
    for (const bucket of ["minimal", "partial", "full"] as const) {
      it(`case ${c.shot_id} / ${bucket}`, () => {
        const row = encodeRow(maskGroups(feats, BUCKET_KEEP[bucket]));
        const exp: (number | null)[] = c.buckets[bucket].row;
        expect(row.length).toBe(exp.length);
        for (let i = 0; i < exp.length; i++) {
          if (exp[i] === null) expect(Number.isNaN(row[i]), `${MODEL_FEATURES[i]}`).toBe(true);
          else expect(row[i], MODEL_FEATURES[i]).toBeCloseTo(exp[i] as number, 5);
        }
      });
    }
  }
});

describe("calibration + bucket parity", () => {
  for (const c of fixtures.cases) {
    for (const bucket of ["minimal", "partial", "full"] as const) {
      it(`case ${c.shot_id} / ${bucket} xg`, () => {
        const { x, y } = calibrators[bucket];
        expect(interp(x, y, c.buckets[bucket].raw)).toBeCloseTo(c.buckets[bucket].xg, 4);
      });
    }
  }
  it("pickBucket matches how each fixture was labelled", () => {
    for (const c of fixtures.cases) {
      const b = pickBucket(presentGroups(c.input as ShotInput));
      expect(["minimal", "partial", "full"]).toContain(b);
    }
  });
});
