// Parity: the TypeScript PSxG port must reproduce training/psxg_feature_fixtures.json
// (generated by training/export_psxg_onnx.py from real on-target StatsBomb shots).

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { interp } from "./calibrate";
import { BUCKET_KEEP, maskGroups } from "./encode";
import { featuresFromInput } from "./features";
import { encodePsxgRow, GOALMOUTH_COLUMNS, PSXG_MODEL_FEATURES, psxgRow } from "./psxgFeatures";
import type { GoalPoint, ShotInput } from "./types";

const here = new URL(".", import.meta.url).pathname;
const fixtures = JSON.parse(readFileSync(join(here, "__fixtures__/psxg_feature_fixtures.json"), "utf8"));
const spec = JSON.parse(readFileSync(join(here, "../../public/model/psxg_feature_spec.json"), "utf8"));
const calibrators = JSON.parse(readFileSync(join(here, "../../public/model/psxg_calibrators.json"), "utf8"));

const isNil = (v: unknown) => v === null || v === undefined || (typeof v === "number" && Number.isNaN(v));

describe("psxg feature spec agreement", () => {
  it("PSXG_MODEL_FEATURES matches the shipped ONNX input order", () => {
    expect(PSXG_MODEL_FEATURES).toEqual(spec.model_features);
  });
  it("GOALMOUTH_COLUMNS matches training", () => {
    expect(GOALMOUTH_COLUMNS).toEqual(spec.goalmouth_columns);
  });
});

describe("psxgRow parity (full pre-shot detail)", () => {
  for (const c of fixtures.cases) {
    it(`case ${c.shot_id}`, () => {
      const preshot = featuresFromInput(c.input as ShotInput);
      const got = psxgRow(c.input as ShotInput, preshot, c.goalmouth as GoalPoint);
      for (const key of Object.keys(c.features)) {
        const exp = c.features[key];
        if (isNil(exp)) expect(isNil(got[key]), `${key} expected nil`).toBe(true);
        else if (typeof exp === "number") expect(got[key] as number, key).toBeCloseTo(exp, 6);
        else expect(got[key], key).toBe(exp);
      }
    });
  }
});

describe("encodePsxgRow + maskGroups parity", () => {
  for (const c of fixtures.cases) {
    const preshot = featuresFromInput(c.input as ShotInput);
    for (const bucket of ["minimal", "partial", "full"] as const) {
      it(`case ${c.shot_id} / ${bucket}`, () => {
        const masked = maskGroups(preshot, BUCKET_KEEP[bucket]);
        const row = encodePsxgRow(psxgRow(c.input as ShotInput, masked, c.goalmouth as GoalPoint));
        const exp: (number | null)[] = c.buckets[bucket].row;
        expect(row.length).toBe(exp.length);
        for (let i = 0; i < exp.length; i++) {
          if (exp[i] === null) expect(Number.isNaN(row[i]), `feature ${i}`).toBe(true);
          else expect(row[i], `feature ${i}`).toBeCloseTo(exp[i] as number, 5);
        }
      });
    }
  }
});

describe("psxg calibration parity", () => {
  for (const c of fixtures.cases) {
    for (const bucket of ["minimal", "partial", "full"] as const) {
      it(`case ${c.shot_id} / ${bucket} psxg`, () => {
        const { x, y } = calibrators[bucket];
        expect(interp(x, y, c.buckets[bucket].raw)).toBeCloseTo(c.buckets[bucket].xg, 4);
      });
    }
  }
});
